# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from assets.animated_ui import AnimatedComboBox


class Ui_CreateWindow(object):
    def setupUi(self, CreateWindow):
        CreateWindow.setObjectName("CreateWindow")
        CreateWindow.resize(300, 390)
        self.list_mods = QtWidgets.QListWidget(CreateWindow)
        self.list_mods.setGeometry(QtCore.QRect(0, 90, 301, 192))
        self.list_mods.setObjectName("list_mods")
        self.comboBox_avalableVersions = AnimatedComboBox(CreateWindow)
        self.comboBox_avalableVersions.setGeometry(QtCore.QRect(0, 30, 171, 30))
        self.comboBox_avalableVersions.setObjectName("comboBox_avalableVersions")
        self.comboBox_avalableTypes = AnimatedComboBox(CreateWindow)
        self.comboBox_avalableTypes.setGeometry(QtCore.QRect(0, 0, 300, 30))
        self.comboBox_avalableTypes.setObjectName("comboBox_avalableTypes")
        self.button_mod_add = QtWidgets.QPushButton(CreateWindow)
        self.button_mod_add.setGeometry(QtCore.QRect(0, 280, 91, 31))
        self.button_mod_add.setObjectName("button_mod_add")
        self.button_mod_remove = QtWidgets.QPushButton(CreateWindow)
        self.button_mod_remove.setGeometry(QtCore.QRect(90, 280, 91, 31))
        self.button_mod_remove.setObjectName("button_mod_remove")
        self.label = QtWidgets.QLabel(CreateWindow)
        self.label.setGeometry(QtCore.QRect(10, 70, 101, 21))
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.button_create = QtWidgets.QPushButton(CreateWindow)
        self.button_create.setGeometry(QtCore.QRect(0, 360, 300, 30))
        self.button_create.setObjectName("button_create")
        self.line_launcherName = QtWidgets.QLineEdit(CreateWindow)
        self.line_launcherName.setGeometry(QtCore.QRect(0, 330, 300, 30))
        self.line_launcherName.setText("")
        self.line_launcherName.setObjectName("line_launcherName")
        self.label_2 = QtWidgets.QLabel(CreateWindow)
        self.label_2.setGeometry(QtCore.QRect(10, 310, 47, 21))
        self.label_2.setObjectName("label_2")
        self.comboBox_avalableSubTypes = AnimatedComboBox(CreateWindow)
        self.comboBox_avalableSubTypes.setEnabled(True)
        self.comboBox_avalableSubTypes.setGeometry(QtCore.QRect(170, 30, 131, 30))
        self.comboBox_avalableSubTypes.setBaseSize(QtCore.QSize(0, 0))
        self.comboBox_avalableSubTypes.setObjectName("comboBox_avalableSubTypes")

        self.retranslateUi(CreateWindow)
        QtCore.QMetaObject.connectSlotsByName(CreateWindow)

    def retranslateUi(self, CreateWindow):
        _translate = QtCore.QCoreApplication.translate
        CreateWindow.setWindowTitle(_translate("CreateWindow", "Dialog"))
        self.button_mod_add.setText(_translate("CreateWindow", "Add"))
        self.button_mod_remove.setText(_translate("CreateWindow", "Remove"))
        self.label.setText(_translate("CreateWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Mod List</span></p></body></html>"))
        self.button_create.setText(_translate("CreateWindow", "Create"))
        self.label_2.setText(_translate("CreateWindow", "Name:"))
