# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from assets.animated_ui import AnimatedComboBox


class Ui_EditWindow(object):
    def setupUi(self, EditWindow):
        EditWindow.setObjectName("EditWindow")
        EditWindow.resize(300, 340)
        self.comboBox_avalableVersions = AnimatedComboBox(EditWindow)
        self.comboBox_avalableVersions.setGeometry(QtCore.QRect(0, 20, 300, 30))
        self.comboBox_avalableVersions.setObjectName("comboBox_avalableVersions")
        self.label = QtWidgets.QLabel(EditWindow)
        self.label.setGeometry(QtCore.QRect(10, 0, 121, 21))
        self.label.setObjectName("label")
        self.button_mod_remove = QtWidgets.QPushButton(EditWindow)
        self.button_mod_remove.setGeometry(QtCore.QRect(90, 270, 91, 31))
        self.button_mod_remove.setObjectName("button_mod_remove")
        self.list_mods = QtWidgets.QListWidget(EditWindow)
        self.list_mods.setGeometry(QtCore.QRect(0, 80, 301, 192))
        self.list_mods.setObjectName("list_mods")
        self.button_mod_add = QtWidgets.QPushButton(EditWindow)
        self.button_mod_add.setGeometry(QtCore.QRect(0, 270, 91, 31))
        self.button_mod_add.setObjectName("button_mod_add")
        self.label_2 = QtWidgets.QLabel(EditWindow)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 101, 21))
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.button_create = QtWidgets.QPushButton(EditWindow)
        self.button_create.setGeometry(QtCore.QRect(0, 310, 300, 30))
        self.button_create.setObjectName("button_create")

        self.retranslateUi(EditWindow)
        QtCore.QMetaObject.connectSlotsByName(EditWindow)

    def retranslateUi(self, EditWindow):
        _translate = QtCore.QCoreApplication.translate
        EditWindow.setWindowTitle(_translate("EditWindow", "Dialog"))
        self.label.setText(_translate("EditWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Used version</span></p></body></html>"))
        self.button_mod_remove.setText(_translate("EditWindow", "Remove"))
        self.button_mod_add.setText(_translate("EditWindow", "Add"))
        self.label_2.setText(_translate("EditWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Mod List</span></p></body></html>"))
        self.button_create.setText(_translate("EditWindow", "Save"))
