# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'download_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DownloadWindow(object):
    def setupUi(self, DownloadWindow):
        DownloadWindow.setObjectName("DownloadWindow")
        DownloadWindow.resize(300, 51)
        self.progressBar = QtWidgets.QProgressBar(DownloadWindow)
        self.progressBar.setGeometry(QtCore.QRect(0, 0, 300, 30))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(DownloadWindow)
        self.label.setGeometry(QtCore.QRect(10, 30, 291, 21))
        self.label.setObjectName("label")

        self.retranslateUi(DownloadWindow)
        QtCore.QMetaObject.connectSlotsByName(DownloadWindow)

    def retranslateUi(self, DownloadWindow):
        _translate = QtCore.QCoreApplication.translate
        DownloadWindow.setWindowTitle(_translate("DownloadWindow", "Dialog"))
        self.label.setText(_translate("DownloadWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">State</span></p></body></html>"))
