# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from assets.animated_ui import AnimatedComboBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 217)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_avalableVersions = AnimatedComboBox(self.centralwidget)
        self.comboBox_avalableVersions.setGeometry(QtCore.QRect(0, 90, 300, 30))
        self.comboBox_avalableVersions.setObjectName("comboBox_avalableVersions")
        self.button_check = QtWidgets.QPushButton(self.centralwidget)
        self.button_check.setGeometry(QtCore.QRect(160, 120, 71, 31))
        self.button_check.setObjectName("button_check")
        self.button_start = QtWidgets.QPushButton(self.centralwidget)
        self.button_start.setGeometry(QtCore.QRect(0, 120, 161, 31))
        self.button_start.setObjectName("button_start")
        self.button_createNew = QtWidgets.QPushButton(self.centralwidget)
        self.button_createNew.setGeometry(QtCore.QRect(0, 150, 301, 31))
        self.button_createNew.setObjectName("button_createNew")
        self.button_delete = QtWidgets.QPushButton(self.centralwidget)
        self.button_delete.setGeometry(QtCore.QRect(230, 120, 71, 31))
        self.button_delete.setObjectName("button_delete")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(0, 20, 300, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(6, 2, 121, 21))
        self.label.setObjectName("label")
        self.comboBox_avalableTypes = AnimatedComboBox(self.centralwidget)
        self.comboBox_avalableTypes.setGeometry(QtCore.QRect(0, 60, 300, 30))
        self.comboBox_avalableTypes.setObjectName("comboBox_avalableTypes")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_check.setText(_translate("MainWindow", "Check"))
        self.button_start.setText(_translate("MainWindow", "Start"))
        self.button_createNew.setText(_translate("MainWindow", "Create new VLauncher"))
        self.button_delete.setText(_translate("MainWindow", "Delete"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Nickname</span></p></body></html>"))
